/**
 * export_addresses.ts — YearRing Closed Beta: Push Deployed Addresses to Frontend
 *
 * Must run AFTER verify_deployment.ts passes all checks.
 * Reads deployments/closed_beta_<network>.json and rewrites
 * frontend/src/contracts/addresses.ts with the real deployed addresses.
 *
 * Usage:
 *   npx hardhat run scripts/closed_beta/export_addresses.ts --network base
 *   npx hardhat run scripts/closed_beta/export_addresses.ts --network hardhat
 *
 * Safe: writes a backup before overwriting (addresses.ts.bak).
 */

import { network } from "hardhat";
import * as fs from "fs";
import * as path from "path";

async function main() {
  const deploymentsPath = path.join(
    __dirname, "../../deployments", `closed_beta_${network.name}.json`
  );

  if (!fs.existsSync(deploymentsPath)) {
    throw new Error(
      `Deployment record not found: ${deploymentsPath}\n` +
      `Run deploy_core_beta.ts, setup_roles.ts, verify_deployment.ts first.`
    );
  }

  const dep = JSON.parse(fs.readFileSync(deploymentsPath, "utf8"));
  const c   = dep.contracts as Record<string, string>;

  function addr(key: string, fallback?: string): string {
    return c[key] ?? fallback ?? "0x0000000000000000000000000000000000000000";
  }

  const ZERO = "0x0000000000000000000000000000000000000000";

  // Resolved addresses
  const USDC                       = addr("USDC");
  const YearRingCoreVaultV01       = addr("YearRingCoreVaultV01");
  const TreasuryV02                = addr("TreasuryV02");
  const PointsToken                = addr("PointsToken");
  const LockLedgerV02              = addr("LockLedgerV02");
  const LockBenefitV02             = addr("LockBenefitV02");
  const LockPointsRebateManagerV02 = addr("LockPointsRebateManagerV02");
  const BeneficiaryModuleV02       = addr("BeneficiaryModuleV02");
  const UserStateEngineV02         = addr("UserStateEngineV02");
  const MetricsLayerV02            = addr("MetricsLayerV02");
  const GovernanceSignalV02        = addr("GovernanceSignalV02");
  const ClaimLedger                = addr("ClaimLedger");

  const outputTs = `// Closed Beta deployment addresses — ${network.name} — ${dep.timestamp}
// Auto-generated by scripts/closed_beta/export_addresses.ts
// DO NOT EDIT MANUALLY
export const ADDRESSES = {
  USDC:                      "${USDC}" as \`0x\${string}\`,
  YearRingCoreVaultV01:      "${YearRingCoreVaultV01}" as \`0x\${string}\`,
  TreasuryV02:               "${TreasuryV02}" as \`0x\${string}\`,
  PointsToken:               "${PointsToken}" as \`0x\${string}\`,
  LockLedgerV02:             "${LockLedgerV02}" as \`0x\${string}\`,
  LockBenefitV02:            "${LockBenefitV02}" as \`0x\${string}\`,
  LockPointsRebateManagerV02:"${LockPointsRebateManagerV02}" as \`0x\${string}\`,
  BeneficiaryModuleV02:      "${BeneficiaryModuleV02}" as \`0x\${string}\`,
  UserStateEngineV02:        "${UserStateEngineV02}" as \`0x\${string}\`,
  MetricsLayerV02:           "${MetricsLayerV02}" as \`0x\${string}\`,
  GovernanceSignalV02:       "${GovernanceSignalV02}" as \`0x\${string}\`,
  ClaimLedger:               "${ClaimLedger}" as \`0x\${string}\`,
} as const
`;

  const frontendPath = path.join(
    __dirname, "../../frontend/src/contracts/addresses.ts"
  );

  // Backup existing file
  if (fs.existsSync(frontendPath)) {
    fs.copyFileSync(frontendPath, frontendPath + ".bak");
    console.log("  ℹ  Backup saved → addresses.ts.bak");
  }

  fs.writeFileSync(frontendPath, outputTs);

  console.log("\n" + "=".repeat(68));
  console.log("  ADDRESSES EXPORTED");
  console.log("=".repeat(68));
  console.log(`  Source: ${deploymentsPath}`);
  console.log(`  Target: ${frontendPath}`);
  console.log("");
  console.log(`  USDC                       ${USDC}`);
  console.log(`  YearRingCoreVaultV01       ${YearRingCoreVaultV01}`);
  console.log(`  TreasuryV02                ${TreasuryV02}`);
  console.log(`  PointsToken                ${PointsToken}`);
  console.log(`  LockLedgerV02              ${LockLedgerV02}`);
  console.log(`  LockBenefitV02             ${LockBenefitV02}`);
  console.log(`  LockPointsRebateManagerV02 ${LockPointsRebateManagerV02}`);
  console.log(`  BeneficiaryModuleV02       ${BeneficiaryModuleV02}`);
  console.log(`  UserStateEngineV02         ${UserStateEngineV02}`);
  console.log(`  MetricsLayerV02            ${MetricsLayerV02}`);
  console.log(`  GovernanceSignalV02        ${GovernanceSignalV02}`);
  console.log(`  ClaimLedger                ${ClaimLedger}`);
  console.log("=".repeat(68));
  console.log("\n  Run `npm run build` in frontend/ to verify the updated addresses compile.");

  // Flag TBD addresses
  const tbdKeys = Object.entries({
    YearRingCoreVaultV01, TreasuryV02, PointsToken, LockLedgerV02,
    LockBenefitV02, LockPointsRebateManagerV02, BeneficiaryModuleV02,
    UserStateEngineV02, MetricsLayerV02, GovernanceSignalV02, ClaimLedger,
  }).filter(([, v]) => v === ZERO).map(([k]) => k);

  if (tbdKeys.length > 0) {
    console.log("\n  ⚠  Still TBD (zero address):", tbdKeys.join(", "));
    console.log("     These will be read as disabled in the frontend.");
  }
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
