// Closed Beta deployment addresses — base — 2026-05-05T16:10:02.920Z
// Auto-generated by scripts/closed_beta/export_addresses.ts
// Extended manually with infrastructure addresses (Phase 3 — 2026-05-07)
// Sources: deployments/closed_beta_base.json, deployments/base.json, docs/CONTRACT_ADDRESSES.md
export const ADDRESSES = {
  // ── Core protocol ────────────────────────────────────────────────────────────
  USDC:                       "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913" as `0x${string}`,
  YearRingCoreVaultV01:       "0x2D2C7BbE92571FF28A23e44d19232e9137F3a310" as `0x${string}`,
  TreasuryV02:                "0xA8a6BE4B0Cf96b43169EB9FeB7d905bfc301a083" as `0x${string}`,
  PointsToken:                "0xe8f731bef3Ebda21Da6aa4a2B061448F7842e90c" as `0x${string}`,
  // ── Lock / Commitment ────────────────────────────────────────────────────────
  LockLedgerV02:              "0x66A4d021642bE3d0916aabA69c415E6D62333A23" as `0x${string}`,
  LockBenefitV02:             "0xD126f3ff0f3A88bF0a9Ad139C2B4A83afb1121c1" as `0x${string}`,
  LockPointsRebateManagerV02: "0x03987638d7a0522c2e1521714e46D486628c87a0" as `0x${string}`,
  // ── Supporting modules ───────────────────────────────────────────────────────
  BeneficiaryModuleV02:       "0xcb201afB89E4f5820b3ab19476501ca0A005bab5" as `0x${string}`,
  UserStateEngineV02:         "0x9D0fa30798E8f6F13185571F1033EB26Bae8aac0" as `0x${string}`,
  MetricsLayerV02:            "0x50930AFd56159501801593c8874aA567dd3B6B8E" as `0x${string}`,
  GovernanceSignalV02:        "0xDc297daC28ADF25B790CdF4F6Bd17dc63e8Aa5a0" as `0x${string}`,
  ClaimLedger:                "0x311A7b06CF01c0E2Cb22935723B2496F2F493C91" as `0x${string}`,
  // ── Strategy infrastructure ──────────────────────────────────────────────────
  // Source: deployments/closed_beta_base.json
  StrategyManagerV01:         "0x7359388D2402a1C7494bE45ecC20c95C837f8692" as `0x${string}`,
  AaveV3StrategyV01:          "0xE412435673f630b8546567b8cFadc6A4852fef73" as `0x${string}`,
  // ── Governance infrastructure ────────────────────────────────────────────────
  // Source: deployments/base.json + docs/CONTRACT_ADDRESSES.md (Timelock reused across deployments)
  ProtocolTimelockV02:        "0x054Cb2c32D6062B291420584dE2e5952C372cDD6" as `0x${string}`,
  // Source: deployments/closed_beta_base.json → config.guardian
  Guardian:                   "0xC8052cF447d429f63E890385a6924464B85c5834" as `0x${string}`,
  // Safe / Multisig: Not configured — no multisig deployed for closed beta
} as const
